##########################################################
# Author      : Jerzy 'Yuri' Kramarz (op7ic)             #
# Version     : 1.0                                      #
# Type        : Terraform/Ansible                        #
# Description : BlueTeam.Lab. See README.md for details  # 
##########################################################
---
- name: Configure Wazuh Server
  hosts: wazuh
  gather_facts: no
  roles:
  - role: fleetserver
    tags: [ fleetserver ]
  - role: wazuhserver
    tags: [ wazuhserver ]
  - role: velociraptorserver
    tags: [ velociraptorserver ]