name: Test de Détection

on:
  push:
    paths:
      - 'Scripts/**'
      - 'Docs/Detection/**'

jobs:
  detection-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Python
        run: pip install -r requirements.txt && flake8 Scripts/python
      - name: Validate JSON
        run: jq empty Dashboards/grafana_dashboard.json
